version: '3.8'
services:
  db:
    image: postgres:15
    container_name: blog-trail-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
      POSTGRES_DB: blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
